### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: 9O330Qezf04cfa94778f158dy7sHXxf5

origin=64999&destination=64942&weight=1000&courier=jne